Infra : 파이프라인 최적화 테스트 3

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -63,7 +63,7 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-    needs: push-to-registry
+    needs: build
     steps:
       - name: Download Docker Image Artifact
         uses: actions/download-artifact@v3
@@ -96,21 +96,23 @@ jobs:
               echo "Directory $DEPLOYMENT_DIR does not exist. Creating it."
               mkdir -p "$DEPLOYMENT_DIR"
             fi
-
-            cd "$DEPLOYMENT_DIR"
-
-            # Verify if the Docker image file exists
-            if [ ! -f "server-image.tar" ]; then
-              echo "Docker image file server-image.tar not found in $DEPLOYMENT_DIR"
-              exit 1
-            fi
-
+            
+            cd $DEPLOYMENT_DIR
+            
             # Docker 이미지 로드
             if ! sudo docker load -i server-image.tar; then
               echo "Failed to load Docker image"
               exit 1
             fi
-
+            
+            cd "$DEPLOYMENT_DIR"
+            # Verify if the Docker image file exists
+            if [ ! -f "server-image.tar" ]; then
+              echo "Docker image file server-image.tar not found in $DEPLOYMENT_DIR"
+              exit 1
+            fi
+            
+            
             # 컨테이너 실행
             sudo docker stop now-here-server || true
             sudo docker rm now-here-server || true
@@ -127,6 +129,5 @@ jobs:
               echo "Failed to run Docker container"
               exit 1
             fi
-
             # Show container logs for debugging
             sudo docker logs now-here-server
