Infra : 파이프라인 최적화 테스트 1 (Artifact 사용)

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -3,18 +3,17 @@ name: Build and Deploy Spring Boot to OCI using Docker
 on:
   push:
     branches:
-      - prod
+      - infra/24-unauthorized
 
 jobs:
-  build-and-deploy:
+  build:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2  
+        uses: docker/setup-buildx-action@v2
 
       - name: Cache Docker layers
         uses: actions/cache@v2
@@ -23,23 +22,54 @@ jobs:
           key: ${{ runner.os }}-docker-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-docker-
-            
-      - name: Log in to Github Container Registry
-        uses : docker/login-action@v2
-        with :
-          registry : ghcr.io
-          username : ${{ github.actor }}
-          password : ${{ secrets.GHP_TOKEN }}
 
-      - name: Build and Push Docker Image
+      - name: Build Docker Image
         run: |
           docker buildx build --cache-from type=local,src=/tmp/.buildx-cache \
                               --cache-to type=local,dest=/tmp/.buildx-cache \
-                              -t ghcr.io/${{ github.repository }}/server-image:lastest \
-                              --push .
+                              -t server-image:${{ github.sha }} \
+                              --output type=docker,dest=server-image.tar .
+          echo "::set-output name=image-sha::${{ github.sha }}"
 
+      - name: Upload Docker Image Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: docker-image
+          path: server-image.tar
 
-      # PostgreSQL VM 접속 및 상태 확인 단계
+  push-to-registry:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download Docker Image Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: docker-image
+
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GHP_TOKEN }}
+
+      - name: Load and Push Docker Image to GitHub Container Registry
+        run: |
+          # Load the image from the artifact
+          docker load -i server-image.tar
+          # Tag and push the image
+          docker tag server-image:${{ github.sha }} ghcr.io/${{ github.repository }}/server-image:${{ github.sha }}
+          docker push ghcr.io/${{ github.repository }}/server-image:${{ github.sha }}
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: push-to-registry
+    steps:
+      - name: Download Docker Image Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: docker-image
+
       - name: Check and Start PostgreSQL on Separate VM
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -47,15 +77,14 @@ jobs:
           username: ${{ secrets.PS_VM_USERNAME }}
           key: ${{ secrets.PS_VM_PRIVATE_KEY }}
           script: |
-            if systemctl is-active --quiet postgresql@14-main; then
+            if systemctl is-active --quiet postgresql; then
               echo "PostgreSQL is already running."
             else
               echo "PostgreSQL is not running. Starting PostgreSQL..."
               sudo systemctl start postgresql
             fi
 
-      # 애플리케이션 VM 배포 단계
-      - name: Deploy Spring Boot on OCI VM
+      - name: Deploy Spring Boot Application on OCI VM
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.OCI_VM_IP }}
@@ -67,18 +96,16 @@ jobs:
               echo "Directory $DEPLOYMENT_DIR does not exist. Creating it."
               mkdir -p "$DEPLOYMENT_DIR"
             fi
-            
+
             cd "$DEPLOYMENT_DIR"
 
-            # GitHub Container Registry 로그인
-            echo ${{ secrets.GHP_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-          
-            # Docker 이미지 Pull
-            if ! sudo docker pull ghcr.io/${{ github.repository }}/server-image:lastest; then
-              echo "Failed to pull Docker image"
+            # Docker 이미지 로드
+            if ! sudo docker load -i /home/username/server-image.tar; then
+              echo "Failed to load Docker image"
               exit 1
             fi
-            
+
+            # 컨테이너 실행
             sudo docker stop now-here-server || true
             sudo docker rm now-here-server || true
             if ! sudo docker run -d --name now-here-server -p 8080:8080 \
@@ -90,7 +117,7 @@ jobs:
               -e XOR_KEY=${{ secrets.XOR_KEY }} \
               -e SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }} \
               -e SLACK_INQUIRY_WEBHOOK_URL=${{ secrets.SLACK_INQUIRY_WEBHOOK_URL }} \
-              ghcr.io/${{ github.repository }}/server-image:lastest; then
+              server-image:${{ github.sha }}; then
               echo "Failed to run Docker container"
               exit 1
             fi
